#ifndef VGA_COLORS_H_
#define VGA_COLORS_H_

/* Place for storing all the common vga colors */

enum VGA_COLORS {
  VGA_COLOR_BLACK,
  VGA_COLOR_BLUE,
  VGA_COLOR_GREEN,
  VGA_COLOR_CYAN,
  VGA_COLOR_RED,
  VGA_COLOR_MAGENTA,
  VGA_COLOR_BROWN,
  VGA_COLOR_WHITE,
  VGA_COLOR_GRAY,
  VGA_COLOR_LIGHT_BLUE,
  VGA_COLOR_LIGHT_GREEN,
  VGA_COLOR_LIGHT_CYAN,
  VGA_COLOR_LIGHT_RED,
  VGA_COLOR_LIGHT_MAGENTA,
  VGA_COLOR_YELLOW,
  VGA_COLOR_BRIGHT_WHITE,
};

#endif // VGA_COLORS_H_
